@baseurl=http://localhost:8080

###

# mutation
POST {{baseurl}}/query
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation createTodo {
  createTodo(input: { text: "todo", userId: "1" }) {
    user {
      id
    }
    text
    done
  }
}

###

# query
POST {{baseurl}}/query
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query findTodos {
  todos {
    text
    done
    user {
      name
    }
  }
}
